on: workflow_dispatch

jobs:
  use_github_app_token:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v2 # Use a specific version tag
        with:
          app-id: 2902817
          private-key: ${{ secrets.APP_PRIVATE_KEY_PEM }}
          # The installation-id is automatically determined if not provided, 
          # provided the app is installed on the repo where the workflow runs.

      - name: Use the token to make an API request
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" \
          https://api.github.com/repos/sumanshekhar23/Gitdemo/pulls/1
