on: workflow_dispatch

jobs:
  use_github_app_token:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v2 # Use a specific version tag
        with:
          app-id: 2902817
          private-key: ${{ secrets.APP_PRIVATE_KEY_PEM }}
          owner: ${{ github.repository_owner }}
          repositories: |
            skills-hello-github-actions

      - name: Checkout different repo
        uses: actions/checkout@v6
        with:
          repository: 'sumanshekhar23/skills-hello-github-actions'
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Use the token to make an API request
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" \
          https://api.github.com/repos/sumanshekhar23/Gitdemo/pulls/1
